gerblook/models.py
import json
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask import json, jsonify, make_response, g, current_app as app
from flask.ext.sqlalchemy import SQLAlchemy
from sqlalchemy.types import TypeDecorator, Text

from utils import *

class JSONEncodedDict(TypeDecorator):
  impl = Text

  def process_bind_param(self, value, dialect):
    if value is not None:
      value = json.dumps(value)
    return value

  def process_result_value(self, value, dialect):
    if value is not None:
      value = json.loads(value)
    return value

@login_manager.user_loader
def load_user(id):
  return User.query.get(id)

class User(db.Model):
  __tablename__ = 'users'

  id = db.Column(db.Integer(), primary_key=True, nullable=False)
  created = db.Column(db.DateTime(), default=datetime.utcnow, nullable=False)
  updated = db.Column(db.DateTime(), onupdate=datetime.utcnow)
  username = db.Column(db.String(50), nullable=False, unique=True)
  password = db.Column(db.String(100), nullable=False)
  email = db.Column(db.String(200), nullable=False, unique=True)
  enabled = db.Column(db.Boolean(), default=True, nullable=False)
  verified = db.Column(db.Boolean(), default=False, nullable=False)

  projects = db.relationship('Project', order_by=db.desc('projects.created'), backref='user')

  def __str__(self):
    return self.name or self.email

  def __repr__(self):
    return 'User(%s)' % self.id

  def is_authenticated(self):
    return True

  def is_active(self):
    return self.enabled

  def is_anonymous(self):
    return False

  def get_id(self):
    return unicode(self.id)

  def set_password(self, password):
    self.password = generate_password_hash(password, method='pbkdf2:sha256:1000')

  def check_password(self, password):
    return check_password_hash(self.password, password)

class Project(db.Model):
  __tablename__ = 'projects'

  def __repr__(self):
    return 'Project(%s)' % self.id

  id = db.Column(db.String(), primary_key=True, nullable=False)
  created = db.Column(db.DateTime(), default=datetime.utcnow, nullable=False)
  updated = db.Column(db.DateTime(), onupdate=datetime.utcnow)
  name = db.Column(db.String(100))
  public = db.Column(db.Boolean(), default=True, nullable=False)
  expires = db.Column(db.DateTime())
  rendered = db.Column(db.Boolean(), default=False, nullable=False)
  store_gerbers = db.Column(db.Boolean(), default=True, nullable=False)
  width = db.Column(db.Float())
  height = db.Column(db.Float())
  layer_info = db.Column(JSONEncodedDict())
  color_backgorund = db.Column(db.String(20))
  color_copper = db.Column(db.String(20))
  color_silkscreen = db.Column(db.String(20))

  user_id = db.Column(db.Integer(),
    db.ForeignKey('users.id', onupdate='CASCADE', ondelete='CASCADE'))

gerblook/__init__.py
import os
import sys
import pytz
import redis
import logging
from logging import Formatter
from logging.handlers import RotatingFileHandler
from flask import Flask, request, g
from flask.ext.login import current_user

from utils import *
from models import *

SECRET_KEY = 'FIXME PLEASE!'
DATA_DIR = '/tmp/gerblook/'
#IMAGE_SIZE = '500x500'
SOLDERMASK_COLORS = {
  'Green': '#225533',
  'Red': '#cc0000',
  'Blue': '#00284a',
  'Yellow': '#edd400',
  'Black': '#2d2d2d',
  'White': '#e6e6e6',
}
SILKSCREEN_COLORS = {
  'Black': '#1d1d1dff',
  'White': '#eeeeeeff',
}
COPPER_COLORS = {
  'Silver': '#a0a0a0ff',
  'Gold': '#e3bd91ff',
}

def create_app():
  app = Flask(__name__)
  app.config.from_object(__name__)
  app.config.from_envvar('GERBLOOK_SETTINGS', silent=True)

  log_file = app.config.get('LOG_FILE', None)
  if log_file:
    handler = RotatingFileHandler(log_file, maxBytes=10000, backupCount=99)
    handler.setFormatter(Formatter('%(asctime)s %(levelname)s: %(message)s '
      '[in %(pathname)s:%(lineno)d]'))
    handler.setLevel(logging.INFO)
    app.logger.addHandler(handler)

  app.r = redis.StrictRedis()

  login_manager.setup_app(app)
  login_manager.login_view = 'meta.login'

  if not os.path.isdir(app.config['DATA_DIR']):
    try:
      os.mkdir(app.config['DATA_DIR'])
    except OSError:
      sys.stderr.write('Unable to create DATA_DIR\n')
      sys.exit(2)

  app.tz = pytz.utc
  if 'TIMEZONE' in app.config:
    app.tz = pytz.timezone(app.config['TIMEZONE'])

  app.jinja_env.filters['strftime'] = strftime
  app.jinja_env.filters['localtime'] = localtime

  db.init_app(app)
  @app.before_first_request
  def setup():
    db.create_all()

  from gerblook.views.main import mod
  app.register_blueprint(mod)
  from gerblook.views.user import mod
  app.register_blueprint(mod)
  from gerblook.views.meta import mod
  app.register_blueprint(mod)
  return app

gerblook/views/main.py
import os
import sys
import shortuuid
import shutil
import tempfile
import subprocess
import magic
from zipfile import ZipFile
from rarfile import RarFile
from werkzeug import secure_filename
from flask import Blueprint, request, render_template, flash, \
  url_for, send_file, redirect, abort, current_app as app, g
from flask.ext.wtf import Form
from wtforms import FileField, SelectField
from flask.ext.login import login_user, logout_user, login_required, current_user

from gerblook.utils import *
from gerblook.models import *
from gerblook.gerber import *

mod = Blueprint('main', __name__)

class UploadForm(Form):
  gerbers = FileField('Gerber Files')
  soldermask_color = SelectField('Soldermask Color')
  silkscreen_color = SelectField('Silkscreen Color')
  copper_color = SelectField('Copper Color')

@mod.route('/', methods=['GET', 'POST'])
def index():
  errors = []

  form = UploadForm()
  form.soldermask_color.choices = [(x, x) for x in app.config['SOLDERMASK_COLORS'].keys()]
  form.silkscreen_color.choices = [(x, x) for x in app.config['SILKSCREEN_COLORS'].keys()]
  form.copper_color.choices = [(x, x) for x in app.config['COPPER_COLORS'].keys()]

  if form.validate_on_submit():
    tempdir = tempfile.mkdtemp()
    gerberdir = os.path.join(tempdir, 'gerbers')
    os.mkdir(gerberdir)

    gerbers = []
    for f in request.files.getlist('gerbers'):
      mimetype = magic.from_buffer(f.read(1024), mime=True)
      f.seek(0)
      if mimetype == 'application/zip':
        archive = ZipFile(f)
        for member in archive.namelist():
          safe_filename = secure_filename(member)
          extracted_filename = os.path.join(gerberdir, safe_filename)
          open(extracted_filename, 'wb').write(archive.read(member))
          gerbers.append(safe_filename)
      elif mimetype == 'application/x-rar':
        archive_name = os.path.join(tempdir, secure_filename(f.filename))
        f.save(archive_name)
        archive = RarFile(archive_name)
        for member in archive.namelist():
          safe_filename = secure_filename(member)
          extracted_filename = os.path.join(gerberdir, safe_filename)
          open(extracted_filename, 'wb').write(archive.read(member))
          gerbers.append(safe_filename)
      elif mimetype == 'text/plain':
        safe_filename = secure_filename(f.filename)
        f.save(os.path.join(gerberdir, safe_filename))
        gerbers.append(safe_filename)
      else:
        shutil.rmtree(tempdir)
        error = 'That was an unexpected file type. Please upload a zip, rar or selection of gerber files.'
        error += ' Check the <a class="alert-link" href="/faq">FAQ</a> for the supported file names.'
        flash(error, 'error')
        return render_template('index.html', form=form)

    layers = guess_layers(gerbers, gerberdir)
        
    if 'outline' not in layers.keys():
      errors.append("Couldn't find outline layer.")
    if 'top_copper' not in layers.keys():
      errors.append("Couldn't find top copper layer.")
    if 'top_soldermask' not in layers.keys():
      errors.append("Couldn't find top soldermask layer.")
    if 'bottom_copper' not in layers.keys():
      errors.append("Couldn't find bottom copper layer.")
    if 'bottom_soldermask' not in layers.keys():
      errors.append("Couldn't find bottom soldermask layer.")

    if errors:
      shutil.rmtree(tempdir)
    else:
      uid = str(shortuuid.uuid())

      basedir = os.path.join(app.config['DATA_DIR'], uid)
      shutil.move(tempdir, basedir)
      gerberdir = os.path.join(basedir, 'gerbers')
      imagedir = os.path.join(basedir, 'images')
      os.mkdir(imagedir)

      try:
        color_silkscreen = app.config['SILKSCREEN_COLORS'][form.silkscreen_color.data]
      except KeyError:
        color_silkscreen = '#eeeeeeee'

      try:
        color_background = app.config['SOLDERMASK_COLORS'][form.soldermask_color.data]
      except KeyError:
        color_background = '#225533'

      try:
        color_copper = app.config['COPPER_COLORS'][form.copper_color.data]
      except KeyError:
        color_copper = '#a0a0a0ff'


      # Calculate size of gerber and output images
      try:
        w, h = gerber_size(os.path.join(gerberdir, layers['outline'][0]))
      except:
        w, h = 0, 0
      area = w * h
      DPI = '200'
      if area == 0:
        DPI = '200'
      elif area < 500:
        DPI = '600'
      elif area < 1000:
        DPI = '500'
      elif area < 5000:
        DPI = '400'
      elif area < 10000:
        DPI = '300'
      elif area < 20000:
        DPI = '200'

      details = {
        'gerber_size': (w, h),
        'dpi': DPI,
        'color_silkscreen': color_silkscreen,
        'color_background': color_background,
        'color_copper': color_copper,
        'layers': layers,
        'rendered': False,
      }
      detail_file = os.path.join(basedir, 'details.json')
      json.dump(details, open(detail_file, 'w'))

      project = Project()
      project.id = uid
      project.layer_info = layers
      project.width = w
      project.height = h
      project.color_silkscreen = color_silkscreen
      project.color_background = color_background
      project.color_copper = color_copper
      if current_user.is_authenticated():
        project.user = current_user
      db.session.add(project)
      db.session.commit()

      app.r.lpush('gerblook/renderqueue', uid)
      return redirect(url_for('.pcb', uid=uid))

  return render_template('index.html', errors=errors, form=form)

@mod.route('/pcb/<uid>', methods=['GET', 'POST'])
def pcb(uid):
  uid = secure_filename(uid)
  basedir = os.path.join(app.config['DATA_DIR'], uid)
  if not os.path.isdir(basedir):
    abort(404)

  project = Project.query.get(uid)

  detail_file = os.path.join(basedir, 'details.json')
  try:
    details = json.load(open(detail_file))
  except:
    details = {
      'rendered': True,
    }
  images = os.listdir(os.path.join(basedir, 'images'))

  noalpha = False
  if 'noalpha' in request.args:
    noalpha = True

  return render_template('pcb.html', uid=uid, images=images, noalpha=noalpha,
    details=details, project=project)

@mod.route('/pcb/<uid>/state.json', methods=['GET'])
def pcb_state(uid):
  uid = secure_filename(uid)
  basedir = os.path.join(app.config['DATA_DIR'], uid)
  if not os.path.isdir(basedir):
    abort(404)

  return jsonify(progress=app.r.get('gerblook/pcb/%s/render-progress' % uid),
    activity=app.r.get('gerblook/pcb/%s/render-activity' % uid),
    queue_length=app.r.llen('gerblook/renderqueue'))

@mod.route('/image/<uid>/<image>', methods=['GET'])
def image(uid, image):
  uid = secure_filename(uid)
  image = secure_filename(image)
  basedir = os.path.join(app.config['DATA_DIR'], uid)
  if not os.path.isdir(basedir):
    abort(404)

  image = os.path.join(basedir, 'images', image)
  if not os.path.exists(image):
    abort(404)

  return send_file(image)

@mod.route('/faq')
def faq():
  return render_template('faq.html')

gerblook/views/meta.py
from flask import Blueprint, request, render_template, flash, \
  url_for, redirect, abort, current_app as app

from flask.ext.login import login_user, logout_user, login_required, current_user
from wtforms import TextField, PasswordField, SubmitField, validators
from flask.ext.wtf import Form

from gerblook.utils import *
from gerblook.models import *

mod = Blueprint('meta', __name__)

class LoginForm(Form):
  user = TextField('Username or Email', [validators.DataRequired()])
  password = PasswordField('Password', [validators.DataRequired()])

class SignupForm(Form):
  username = TextField('Username', [validators.DataRequired(), validators.Length(min=3, max=50),
    validators.Regexp(r'^[A-Za-z0-9-]+$',
    message='Usernames may only contain alphanumeric characters or dashes.')])
  email = TextField('Email', [validators.DataRequired(), validators.Email()])
  password = PasswordField('Password', [validators.DataRequired(), validators.Length(min=8)])

@mod.route('/signup', methods=('GET', 'POST'))
def signup():
  form = SignupForm()

  if form.validate_on_submit():
    email_dupe = User.query.filter(User.email==form.email.data).first()
    username_dupe = User.query.filter(User.username==form.username.data).first()
    if username_dupe:
      flash("Sorry, that username is either invalid or already in use.", category='error')
    elif email_dupe:
      flash("Sorry, that email is either invalid or already in use.", category='error')
    else:
      user = User()
      user.username = form.username.data
      user.email = form.email.data
      user.set_password(form.password.data)
      db.session.add(user)
      db.session.commit()
      login_user(user, remember=True)
      flash("Thanks for signing up, you're all signed in and ready to go.", category='success')
      return redirect('/')

  return render_template('signup.html', form=form)

@mod.route('/login', methods=('GET', 'POST'))
def login():
  form = LoginForm()

  if form.validate_on_submit():
    user = User.query.filter(db.or_(User.email==form.user.data, User.username==form.user.data)).first()
    if user:
      if user.check_password(form.password.data):
        login_user(user, remember=True)
        flash("Logged you in.", 'success')
        if 'next' in request.args:
          return redirect(request.args['next'])
        else:
          return redirect('/')
      else:
        flash("Sorry, we couldn't find your username and password combination.", category='warning')
    else:
      flash("Sorry, we couldn't find your username and password combination.", category='warning')

  return render_template('login.html', form=form)

@mod.route('/logout')
def logout():
  logout_user()
  return redirect('/')

gerblook/views/user.py
from flask import Blueprint, request, render_template, flash, \
  url_for, redirect, abort, current_app as app
from flask.ext.login import login_user, logout_user, login_required, current_user

from gerblook.utils import *
from gerblook.models import *

mod = Blueprint('user', __name__)

@mod.route('/<username>', methods=('GET',))
@login_required
def home(username):
  return render_template('home.html')

@mod.route('/<username>/projects', methods=('GET',))
@login_required
def projects(username):
  return render_template('projects.html')

gerblook/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}GerbLook{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base.css') }}" />
  <style type="text/css">
    body {
      padding-top   : 65px;
    }
  </style>
  {% block extrahead %}{% endblock %}
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><b>{{ config.APP_NAME|default('GerbLook') }}</b></a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li{% if active == 'faq' %} class="active"{% endif %}><a href="/faq">FAQ</a></li>
          {% block extranav %}{% endblock %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated() %}
          <li class="dropdown">
            <a class="dropdown-toggle" role="button" data-toggle="dropdown" href="#">
              <i class="glyphicon glyphicon-user"></i> {{ current_user.username }}
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{{ url_for('user.projects', username=current_user.username) }}">Projects</a></li>
            </ul>
          </li>
          <li><a href="/logout"><i class="glyphicon glyphicon-log-out"></i> Sign out</a></li>
          {% else %}
          <li><a href="/signup"><i class="glyphicon glyphicon-user"></i> Sign up</a></li>
          <li><a href="/login"><i class="glyphicon glyphicon-log-in"></i> Sign in</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      {% with messages = get_flashed_messages(category_filter=["error"]) %}
      {% if messages %}
      {% for message in messages %}
      <div class="col-md-10 col-md-offset-1 alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      {% with messages = get_flashed_messages(category_filter=["warning"]) %}
      {% if messages %}
      {% for message in messages %}
      <div class="col-md-10 col-md-offset-1 alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      {% with messages = get_flashed_messages(category_filter=["success"]) %}
      {% if messages %}
      {% for message in messages %}
      <div class="col-md-10 col-md-offset-1 alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      {% with messages = get_flashed_messages(category_filter=["info"]) %}
      {% if messages %}
      {% for message in messages %}
      <div class="col-md-10 col-md-offset-1 alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message|safe }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </div>
    {% block content %}{% endblock %}
    <hr>
    <footer>
      <p class="muted">Sponsored by <a href="http://nicegear.co.nz/">nicegear.co.nz</a>. Rendered using <a href="http://gerbv.gpleda.org/">Gerbv</a> and <a href="http://www.imagemagick.org/">ImageMagick</a>.</p>
    </footer>
  </div>
  <script src="{{ url_for('static', filename='jquery-1.11.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='jquery.ajaxfileupload.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap.file-input.js') }}"></script>
  <script src="{{ url_for('static', filename='base.js') }}"></script>
  <script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(["trackPageView"]);
    _paq.push(["enableLinkTracking"]);

    (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://stats.nice.net.nz/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "3"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
    })();
  </script>
  {% block extrabody %}{% endblock %}
</body>
</html>

gerblook/templates/faq.html
{% extends "base.html" %}

{% block extrabody %}
{% endblock %}

{% block content %}
<dl>
  <dt>What is a GerbLook?</dt>
  <dd>GerbLook is an online viewer which renders images so you can "<strong>look</strong>" at "<strong>gerber</strong>" files. Gerber files are used for manufacturing printed circuit boards (PCBs).</dd>
  <dt>Do you store uploaded gerber files?</dt>
  <dd>Not unless you ask us to. Well, we do store them on disk temporarily while generating the images. Then unless you choose to save them, they are deleted from disk as soon as rendering is completed (or fails), within the same web request.</dd>
  <dt>How are the images created?</dt>
  <dd>Using <a href="http://gerbv.gpleda.org/">Gerbv</a> to render the gerber files to png images and then using some <a href="http://www.imagemagick.org/">ImageMagick</a> magic to merge and apply color to the images.</dd>
  <dt>Why are the images a little bit jaggy?</dt>
  <dd>Antialiasing is not turned which is what makes the nice soft edges you see on some images. This leads to slightly more accurate though not quite as pretty images.</dd>
  <dt>Is the source code available?</dt>
  <dd>Yes, it's on GitHub here; <a href="https://github.com/hadleyrich/GerbLook">https://github.com/hadleyrich/GerbLook</a>.</dd>
  <dt>What gerber file names are expected?</dt>
  <dd>
    The following rules are used to match layers;
    <dl>
      <dt>Board Outline (required)</dt>
      <dd>*.out *.oln *.gm1 *.gbr *.gml *.gko *.gm16 *.gm2</dd>

      <dt>Top Copper (required)</dt>
      <dd>*.gtl (*.cmp, *.top, *toplayer*.ger)</dd>

      <dt>Bottom Copper (required)</dt>
      <dd>*.gbl (*.sol, *.bot, *bottomlayer*.ger)</dd>

      <dt>Top Soldermask (required)</dt>
      <dd>*.gts (*.stc, *.smt, *topsoldermask*.ger)</dd>

      <dt>Bottom Soldermask (required)</dt>
      <dd>*.gbs (*.sts, *.smb, *bottomsoldermask*.ger)</dd>

      <dt>Top Silkscreen</dt>
      <dd>*.gto (*.sst, *topsilkscreen*.ger)</dd>

      <dt>Bottom Silkscreen</dt>
      <dd>*.gbo (*.ssb, *bottomsilkscreen*.ger)</dd>

      <dt>Plated Drills</dt>
      <dd>*.dri *.drl *.drd *.txt</dd>

      <dt>Non-Plated Drills</dt>
      <dd>As for plated drills but with NPTH in the filename</dd>

      <dt>Inner Copper 1</dt>
      <dd>*.g1 *.gl1</dd>

      <dt>Inner Copper 2</dt>
      <dd>*.g2 *.gl2</dd>

      <dt>Inner Copper 3</dt>
      <dd>*.g3 *.gl3</dd>

      <dt>Inner Copper 4</dt>
      <dd>*.g4 *.gl4</dd>

      <dt>Inner Copper 5</dt>
      <dd>*.g5 *.gl5</dd>

      <dt>Inner Copper 6</dt>
      <dd>*.g6 *.gl6</dd>

      <dt>Inner Copper 7</dt>
      <dd>*.g7 *.gl7</dd>
    </dl>
    The * stands for any string of characters. There are also various other rules to try and fuzzy match based on the contents of the filename but if you stick to the above you should be fine.
  </dd>
</dl>
{% endblock %}

gerblook/templates/home.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

gerblook/templates/index.html
{% extends "base.html" %}

{% from "macros.html" import form_field %}

{% block extrabody %}
{% endblock %}

{% block content %}

{% if errors %}
<div class="col-md-10 col-md-offset-1 alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <ul class="unstyled">
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
    </ul>
</div>
{% endif %}

<div class="container-fluid">
    
    <div class="panel panel-default">
        <div class="panel-heading">Upload your Gerber Files</div>
        <div class="panel-body">
            <form id="gerber-form" method="POST" enctype="multipart/form-data" class="form-horizontal" role="form">
                {{ form.hidden_tag() }}
                {{ form_field(form.gerbers, multiple=multiple) }}
                {{ form_field(form.soldermask_color) }}
                {{ form_field(form.silkscreen_color) }}
                {{ form_field(form.copper_color) }}
                <div class="form-group">
                    <label class="col-sm-3"></label>
                    <div class="col-sm-2">
                        <input id="go" class="btn btn-primary" type="submit" value="Go!" />
                    </div>
                </div>
            </form> 
        </div>
    </div>
    
    <p>GerbLook is an online <a href="https://en.wikipedia.org/wiki/Gerber_format">gerber file</a> viewer. Gerber files are used for manufacturing printed circuit boards (PCBs). GerbLook will render and display images of the various layers of your PCB which you can use to inspect what your fabricated board will look like.</p>
    <p>How do you use it? Upload a set of gerber files, can be either zipped, rarred or multiple separate gerber files. Select your soldermask, silkscreen and copper colors. Your gerber files are used to generate the images and then deleted.</p>
    
    <p>GerbLook currently supports up to eight copper layers.</p>
    
    <p>Current issues:</p>
    <ul>
        <li>Does not handle panelised files correctly.</li>
        <li>Some outline lines need to be removed.</li>
        <li>Some images are rendered too large.</li>
        <li>A couple of rendering issues with gerbv
            <ul>
                <li>Files generated from Eagle Cad sometimes have horizontal lines running through polygons</li>
                <li>Some curved lines seem to be slightly offset</li>
            </ul>
        </li>
        <li>May not recognise some gerber file names.</li>
        <li><a href="https://github.com/hadleyrich/GerbLook/issues">Post your issue on GitHub</a></li>
    </ul>
    
    <p>If you have an upload that didn't work or other issues or suggestions, feel free to email <a href="mailto:info@nice.net.nz">info@nice.net.nz</a>. Mention GerbLook in the subject and attach the files if you can.</p>
</div>

{% endblock %}

gerblook/templates/login.html
{% extends "base.html" %}

{% from "macros.html" import form_field %}

{% block content %}
<form id="login-form" method="POST" class="form-horizontal" role="form">
  {{ form.hidden_tag() }}
  {{ form_field(form.user) }}
  {{ form_field(form.password) }}
  <div class="form-group">
    <label class="col-sm-3"></label>
    <div class="col-sm-2">
      <input class="btn btn-primary" type="submit" value="Log in" />
    </div>
  </div>
</form>

{% endblock %}

gerblook/templates/macros.html
{% macro form_field(field) %}
  {% if field.widget.input_type == 'hidden' %}
  <div>{{ field(**kwargs) }}</div>
  {% else %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    {{ field.label(class="control-label col-md-2 col-md-offset-1") }}
    <div class="col-md-2">
      {% set css_class = 'form-control ' + kwargs.pop('class', '') %}
      {{ field(class=css_class, **kwargs) }}
    </div>
    <span class="help-block">
      {% for error in field.errors %}{{ error|e }}{% endfor %}
    </span>
  </div>
  {% endif %}
{% endmacro %}

gerblook/templates/projects.html
{% extends "base.html" %}

{% block content %}
<table class="table table-hover">
  <thead>
<!--
    <tr>
      <td>UUID</td>
      <td>Created</td>
      <td>Name</td>
    </tr>
-->
  </thead>
  <tbody>
  {% for project in current_user.projects %}
  <tr>
    <td><a href="{{ url_for('main.pcb', uid=project.id) }}">{{ project.id }}</a></td>
    <td>{{ project.created|strftime('%Y-%m-%d %H:%M') }} UTC</td>
    <td><a href="{{ url_for('main.pcb', uid=project.id) }}">{{ project.name or '' }}</a></td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

gerblook/templates/signup.html
{% extends "base.html" %}

{% from "macros.html" import form_field %}

{% block content %}
<form id="signup-form" method="POST" class="form-horizontal" role="form">
  {{ form.hidden_tag() }}
  {{ form_field(form.username) }}
  {{ form_field(form.email) }}
  {{ form_field(form.password) }}
  <div class="form-group">
    <label class="col-sm-3"></label>
    <div class="col-sm-2">
      <input class="btn btn-primary" type="submit" value="Sign up" />
    </div>
  </div>
</form>

{% endblock %}